In [1]:
import pandas as pd
import numpy as np
import datetime

# Visualization
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.ticker as tkr
import seaborn as sns
from wordcloud import WordCloud
import descartes
import geopandas

plt.style.use('default')
plt.rcParams.update({'figure.max_open_warning': 0})
pd.options.display.float_format = '{:20,.2f}'.format
sns.set(style="whitegrid")

from plot_mexico import plot_mexico

In [2]:
# Datos de entrenamiento
train = pd.read_csv('../data/train.csv', low_memory=False, \
                    encoding = 'utf-8', index_col='id', parse_dates=['fecha'])
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 240000 entries, 254099 to 121958
Data columns (total 22 columns):
titulo                        234613 non-null object
descripcion                   238381 non-null object
tipodepropiedad               239954 non-null object
direccion                     186928 non-null object
ciudad                        239628 non-null object
provincia                     239845 non-null object
antiguedad                    196445 non-null float64
habitaciones                  217529 non-null float64
garages                       202235 non-null float64
banos                         213779 non-null float64
metroscubiertos               222600 non-null float64
metrostotales                 188533 non-null float64
idzona                        211379 non-null float64
lat                           116512 non-null float64
lng                           116512 non-null float64
fecha                         240000 non-null datetime64[ns]
gimnasio                      240000 non-null float64
usosmultiples                 240000 non-null float64
piscina                       240000 non-null float64
escuelascercanas              240000 non-null float64
centroscomercialescercanos    240000 non-null float64
precio                        240000 non-null float64
dtypes: datetime64[ns](1), float64(15), object(6)
memory usage: 42.1+ MB

In [3]:
train.head()

,titulo,descripcion,tipodepropiedad,direccion,ciudad,provincia,antiguedad,habitaciones,garages,banos,...,idzona,lat,lng,fecha,gimnasio,usosmultiples,piscina,escuelascercanas,centroscomercialescercanos,precio
id,,,,,,,,,,,,,,,,,,,,,
254099,depto. tipo a-402,"depto. interior de 80.15m2, consta de sala com...",Apartamento,Avenida Division del Norte 2005,Benito Juárez,Distrito Federal,nan,2.00,1.00,2.00,...,"23,533.00",nan,nan,2015-08-23,0.00,0.00,0.00,0.00,0.00,"2,273,000.00"
53461,condominio horizontal en venta,"<p>entre sonora y guerrero, atr&aacute;s del h...",Casa en condominio,AV. MEXICO,La Magdalena Contreras,Distrito Federal,10.00,3.00,2.00,2.00,...,"24,514.00",19.31,-99.23,2013-06-28,0.00,0.00,0.00,1.00,1.00,"3,600,000.00"
247984,casa en venta urbi 3 recamaras tonala,descripcion \nla mejor ubicacion residencial e...,Casa,Urbi Tonala,Tonalá,Jalisco,5.00,3.00,2.00,2.00,...,"48,551.00",nan,nan,2015-10-17,0.00,0.00,0.00,0.00,0.00,"1,200,000.00"
209067,casa sola en toluca zinacantepec con credito i...,casa en privada con caseta de vigilancia casas...,Casa,IGNACIO MANUEL ALTAMIRANO 128,Zinacantepec,Edo. de México,1.00,2.00,1.00,1.00,...,"53,666.00",19.30,-99.69,2012-03-09,0.00,0.00,0.00,1.00,1.00,"650,000.00"
185997,paseos del sol,bonito departamento en excelentes condiciones ...,Apartamento,PASEOS DEL SOL,Zapopan,Jalisco,10.00,2.00,1.00,1.00,...,"47,835.00",nan,nan,2016-06-07,0.00,0.00,0.00,0.00,0.00,"1,150,000.00"